// prettier-ignore
export const stubRecipe = [
    {
      id: 1,
      title: "Baklava",
      author: "John Doe",
      difficulty: "Easy",
      featured: true,
      time: 30,
      rating: 4.5,
      description: "This is a delicious recipe that is also eco-friendly.",
      ingredients: [
        "1 cup of flour",
        "1 cup of sugar",
        "1 cup of milk",
        "1 cup of butter",
      ],
      instructions: {
        1: "Mix the flour and sugar together.",
        2: "Add the milk and butter to the mixture.",
        3: "Bake in the oven for 30 minutes.",
      },
      nutrition: {
        calories: "200",
        totalFat: "10g",
        saturatedFat: "5g",
        cholesterol: "50mg",
        sodium: "500mg",
        totalCarbohydrates: "20g",
      },
      movie: "https://www.youtube.com/watch?v=uxJe1cEr1Ts",
      image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
      id: 2,
      title: "Vegan Delight",
      author: "Jane Smith",
      difficulty: "Medium",
      featured: true,
      time: 45,
      rating: 4.0,
      description: "A hearty and satisfying vegan recipe that's full of flavor.",
      ingredients: [
        "1 cup of quinoa",
        "1 can of black beans",
        "1 cup of corn",
        "1 avocado, sliced",
        "2 tbsp of olive oil",
        "1 tbsp of lime juice",
        "Salt and pepper to taste",
      ],
      instructions: {
        1: "Cook the quinoa according to the package instructions.",
        2: "In a large bowl, combine the cooked quinoa, black beans, corn, and avocado.",
        3: "Drizzle with olive oil and lime juice, and season with salt and pepper.",
        4: "Toss everything together and serve.",
      },
      nutrition: {
        calories: "350",
        totalFat: "15g",
        saturatedFat: "2g",
        cholesterol: "0mg",
        sodium: "200mg",
        totalCarbohydrates: "40g",
      },
      movie: "https://www.youtube.com/watch?v=qgSb4VHHUDo&list=PLskHolEkuu5w5bZ-cLH_KRB7I5k5DV-pm",
      image: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
      id: 3,
      title: "Spicy Thai Noodles",
      author: "Alice Johnson",
      difficulty: "Hard",
      featured: true,
      time: 60,
      rating: 4.7,
      description: "A spicy and flavorful Thai noodle dish that will tantalize your taste buds.",
      ingredients: [
        "200g rice noodles",
        "2 tbsp of soy sauce",
        "1 tbsp of fish sauce",
        "1 red chili, sliced",
        "2 cloves of garlic, minced",
        "1 cup of mixed vegetables",
        "2 tbsp of vegetable oil",
        "Fresh cilantro for garnish",
      ],
      instructions: {
        1: "Cook the rice noodles according to the package instructions.",
        2: "In a pan, heat vegetable oil and sauté garlic and chili until fragrant.",
        3: "Add mixed vegetables and stir-fry for a few minutes.",
        4: "Add the cooked noodles, soy sauce, and fish sauce. Stir well.",
        5: "Garnish with fresh cilantro and serve hot.",
      },
      nutrition: {
        calories: "450",
        totalFat: "20g",
        saturatedFat: "4g",
        cholesterol: "30mg",
        sodium: "800mg",
        totalCarbohydrates: "50g",
      },
      movie: "https://www.youtube.com/watch?v=Zb1sW7vY77Y",
      image: "https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg",
    },
    {
      id: 4,
      title: "Classic Italian Pizza",
      author: "Mario Rossi",
      difficulty: "Medium",
      featured: false,
      time: 90,
      rating: 4.8,
      description: "A classic pizza recipe with a crispy crust and rich tomato sauce.",
      ingredients: [
        "2 cups of all-purpose flour",
        "1 cup of warm water",
        "1 packet of yeast",
        "1 cup of tomato sauce",
        "1 cup of shredded mozzarella cheese",
        "1/2 cup of sliced pepperoni",
        "1 tbsp of olive oil",
        "1 tsp of dried oregano",
      ],
      instructions: {
        1: "Mix flour, yeast, and warm water to make the dough. Let it rise for 1 hour.",
        2: "Roll out the dough and place it on a pizza stone.",
        3: "Spread tomato sauce over the dough and top with mozzarella cheese and pepperoni.",
        4: "Bake in a preheated oven at 475°F (245°C) for 15-20 minutes.",
        5: "Remove from oven, drizzle with olive oil, and sprinkle with oregano before serving.",
      },
      nutrition: {
        calories: "600",
        totalFat: "30g",
        saturatedFat: "15g",
        cholesterol: "80mg",
        sodium: "1200mg",
        totalCarbohydrates: "70g",
      },
      movie: "https://www.youtube.com/watch?v=n-VRntrbypI",
      image: "https://images.pexels.com/photos/2181151/pexels-photo-2181151.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
      id: 5,
      title: "Mediterranean Salad",
      author: "Sophia Williams",
      difficulty: "Easy",
      featured: false,
      time: 20,
      rating: 4.3,
      description: "A fresh and vibrant Mediterranean salad that's perfect for a light meal.",
      ingredients: [
        "1 cucumber, diced",
        "1 cup of cherry tomatoes, halved",
        "1/2 cup of Kalamata olives",
        "1/4 cup of red onion, thinly sliced",
        "1/4 cup of feta cheese, crumbled",
        "2 tbsp of olive oil",
        "1 tbsp of red wine vinegar",
        "Salt and pepper to taste",
      ],
      instructions: {
        1: "Combine cucumber, cherry tomatoes, olives, red onion, and feta cheese in a large bowl.",
        2: "In a small bowl, whisk together olive oil, red wine vinegar, salt, and pepper.",
        3: "Pour the dressing over the salad and toss gently to combine.",
        4: "Serve immediately or chill in the refrigerator before serving.",
      },
      nutrition: {
        calories: "150",
        totalFat: "12g",
        saturatedFat: "3g",
        cholesterol: "15mg",
        sodium: "400mg",
        totalCarbohydrates: "10g",
      },
      movie: "https://www.youtube.com/watch?v=mDHQKEJduFM",
      image: "https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
  ];
